### ISSUE TITLE
Remaining TODO List

### ISSUE THREAD

**Issue by PhilippMDoerner** [PhilippMDoerner/ThreadButler#2]
- [x] CONTRIBUTING.md
- [x] Kill-All mechanism via atomic (Done via just a global bool)
- [x] Implement task-threads from PMunch's example
- [x] Require all threads to be global variables that get passed in as parameters
- [x] Go over docs again and make it consistent with the Glossary
- [x] Note that this only supports ARC/ORC
- [ ] Add tests
- [ ] First round of feedback on docs, code and namings

**Comment by PhilippMDoerner** [comment]
Functional Example in question for Task-Threads: 
```nim
import os

var
  thread: Thread[void]
  chan: Channel[string]

proc ourThread() {.thread.} =
  sleep(100)
  chan.send "Hello"
  sleep(100)
  chan.send "World"
  sleep(100)
  chan.send ""

chan.open
createThread(thread, ourThread)
while true:
  let msg = chan.recv
  if msg.len == 0: break
  echo msg

chan.close
echo "Thread completed"
```
```nim
import taskpools
import std/[random, os]

randomize()

var chan: Channel[string]
chan.open()

proc doThing(x: int) =
  sleep(1000)
  let success = chan.trySend("Thing: " & $x)
  if not success:
    echo "Failed! Size: ", chan.peek()

proc main() =
  var tp = Taskpool.new(numThreads = 4)
  
  while true:
    let rnd = rand(0..100000)
    tp.spawn doThing(rnd)
    
    let resp = chan.tryRecv()
    if resp.dataAvailable:
      echo "Client received: ", resp.msg
      
  tp.shutdown()

main()
```

**Comment by PhilippMDoerner** [comment]
We're doing a redesign. It finally clicked about how instead of seeing a single thread as a server, I can regard a single *thread pool* as a server.

So options:
- Spawn a single thread as an actual server which keeps running, has its own state, own threadpool (size configurable via the server object)  etc.
- Run tasks via threadpools. If the threadServer receives some crap that should be outsourced over a task, just run a task on its own threadpool. Tasks also send messages back to the Channel of the thread they spawned from. Intentional limitation to not make this a free for all on who communicates with who. This one is unlikely to be useful for owlkettle as it has GTasks. Though I guess it could be nice to run tasks on the server.

**Comment by PhilippMDoerner** [comment]
For my memo for the later thread:
Remember to fully blame tissatussa for this repo and link to their forum post/issue:
https://forum.nim-lang.org/t/10719

https://github.com/can-lehmann/owlkettle/issues/145

**Comment by PhilippMDoerner** [comment]
With the reimplementation on using a propper actor base this will become obsolet.

**Comment by tissatussa** [comment]
> ..Remember to fully blame tissatussa for this repo and link to their forum post/issue..

did anyone ever solve "my" Issue ?
was it Nim / Owlkettle related ?
