### ISSUE TITLE
TODO Reimplementation

### ISSUE THREAD

**Issue by PhilippMDoerner** [PhilippMDoerner/ThreadButler#7]
Things to finish before fully pushing out the reimplementation of ThreadButler to a more actor-focused approach.

- [ ] ServerActor: Fix: "Taskpool causes spinloop where Thread B continuously tries to steal work from Thread A, causing hotspin"
  - Appears to be a taskpool scope issue: [Issue opened](https://github.com/status-im/nim-taskpools/issues/41)
    - Taskpool cannot be used for this and is fundamentally incompatible with what I wish to achieve here. This boils either down to finding a different threadpool or writing your own.
    --> Can not be fixed, it is easier to just implement your own taskpool, see recent iteration of slacktors
- [ ] ServerActor: Fix: "Exception raised after any await will turn into FutureDefect"
  - If you can't find a propper solution, as a fallback, mandate that `processMessages` must not raise Exceptions and state that procs *must* do perfect exception handling.
  - [Issue asking for advice opened](https://github.com/status-im/nim-chronos/issues/541) | [Forum thread asking for advice](https://forum.nim-lang.org/t/11589)
- [ ] ServerActor: Add finishing all async-work in dispatcher in `serverActorType.gracefulShutdown`
  - Important because it otherwise causes memory leaks. Around 20816 Bytes for 6 messages growing to 20829 for 60000 messages. It doesn't scale that badly so it is at least somewhat static. That it happens at all is annoying as hell. It also goes up slightly the more async calls you have.
- [ ] ServerActor: Docs
- [ ] ServerActor: Tests
- [ ] Actor: Tests
- [ ] Actor: Docs
- [ ] Check how this interacts / can be combined with Rex
